Added GameController, Game Repository,IgameRepository,GameService and…
240401-NET/wwtbam pull request #24
Opened 2024-04-24 19:37 UTC by Jonah314

… IGameService

2024-04-24 19:40 UTC, vircabading submitted a review, later dismissed

2024-04-24 19:43 UTC, kwm0304 requested changes

2024-04-24 19:43 UTC, kwm0304 commented on server/Controllers/GameController.cs
> +    [HttpGet("Games")]
# Can remove ("Games"), [Route("api/[controller]")] it will pull Game from the name of the controller. Right now it would be api/Game/Games

2024-04-24 19:54 UTC, Jonah314 reviewed
Did changes

2024-04-25 01:36 UTC, vircabading commented on server/Controllers/GameController.cs
> +    [HttpGet("Games")]
this part is resolved

2024-04-25 01:40 UTC, vircabading commented
> Program.cs

Jonathan took out the changes to Program.cs to resolve merge conflict.  Can we approve this one without the Program.cs changes then I can make changes to Program.cs once everything is merged to prevent conflicts

2024-04-25 01:41 UTC, vircabading approved these changes

2024-04-25 17:06 UTC, kwm0304 approved these changes

2024-04-25 17:11 UTC, kwm0304 approved these changes

2024-04-25 17:11 UTC, somych1 approved these changes

2024-04-25 17:12 UTC, merged